name: Build CI
on: [push]

jobs:
  rainix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Install dependencies
        run: nix develop -c npm install

      - name: Build
        run: nix develop -c npm run build